### ISSUE TITLE
flip taxonomies (nico wants younger left, older right), order not clear from input file

### ISSUE THREAD

**Issue by rodenhausen** [biosemantics/euler#5]

**Comment by ramorrismorris** [comment]
I suppose that younger means chronologically. I also suppose that an alignment has all it's articulation with the same source taxonomy,  In that case, should the software support composition of alignments T1-->T2-->T3  there will be cases where it is not possible to always have the younger on the left (and, for that matter, cases where the younger is always on the right.) More generally, given two independent partial orders (here "A younger than B" and "A aligns to B", one can always have this problem if three taxonomies are in play. In general one is free to switch orders when there is only a single order.  That's why spreadsheets provide "Order first by Col X and then by Col Y", not "Order by Col X AND by Col Y"
